### ISSUE TITLE
Check the error with predict function

### ISSUE THREAD

**Issue by aluisascosta** [datascience-mobi-2023/topic05_team04#2]
https://github.com/datascience-mobi-2023/topic05_team04/blob/42861e6e59819120082ae99fffdd3392806c8aac/Luis%20Ordner/Blaue_Bib.Rmd#L285

**Comment by aluisascosta** [comment]
Hi Luis, I tried and I think the issue here is that you are not exactly able to use the `predict` function as is. I am not sure why, somehow it's not really possible to predict on different values in this context. You can use the equation only I believe. 

If you want to add a more complex scenario, could be a good idea to apply the linear regression to predict something else. For example, how well will CNV value and/or Achilles score predict gene expression?

**Comment by luisherfurth** [comment]
Hi Ana, I made it work :D The problem, was the naming of the column in the data.frame, because the predict functions looks for the same name used for the predictor in the model... And I had some unnecessary complicated name but figured it out! For the more complex scenario is not enough time rn, because I am fully booked out with other stuff and would like to improve the code we have to this point and not start something new :)
